/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lxf_ndkstring_Hello */

#ifndef _Included_com_lxf_ndkstring_Hello
#define _Included_com_lxf_ndkstring_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lxf_ndkstring_Hello
 * Method:    encode_int
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lxf_ndkstring_Hello_encode_1int
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lxf_ndkstring_Hello
 * Method:    encode_String
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxf_ndkstring_Hello_encode_1String
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_lxf_ndkstring_Hello
 * Method:    decode_String
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxf_ndkstring_Hello_decode_1String
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_lxf_ndkstring_Hello
 * Method:    encode_intArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_lxf_ndkstring_Hello_encode_1intArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
